# https://starship.rs/config/#prompt


# Disable the newline at the start of the prompt
add_newline = false
# Overwrite a default_prompt_order and  use custom prompt_order
# prompt_order=["rust","line_break","package","line_break","character"]
# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10


[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[character]
symbol = "â˜¯"

[directory]
truncation_length = 1
# fish_style_pwd_dir_length = 3

[git_status]
stashed = "âš€"
stashed_count.enabled = true

